# Generated by Django 4.2 on 2024-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Engg Chemistry', 'Engg Chemistry'), ('Comm Skills', 'Comm Skills'), ('Basic Electrical Engg', 'Basic Electrical Engg'), ('Basic Mechanical Engg', 'Basic Mechanical Engg'), ('Engg Mathematics', 'Engg Mathematics')], max_length=30)),
                ('grade', models.CharField(max_length=4)),
                ('credit_points', models.PositiveIntegerField()),
            ],
        ),
    ]
